// <auto-generated />
namespace EmployeeInformationSystem.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class NullableInts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableInts));
        
        string IMigrationMetadata.Id
        {
            get { return "201912241019592_NullableInts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
